<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class FoodSeeder extends Seeder
{
    public function run()
    {
        $foods = [
            [
                'name'        => 'Gulai Ikan Patin Khas Riau',
                'slug'        => 'gulai-ikan-patin-khas-riau',
                'category'    => 'Gulai Utama',
                'price'       => 45000,
                'description' => 'Ikan patin segar khas Sungai Siak dimasak dalam kuah gulai santan kuning melimpah dengan racikan kunyit, lengkuas, serai, dan daun jeruk yang gurih beraroma wangi khas Melayu Riau.',
                'origin'      => 'Pekanbaru, Riau',
                'spice_level' => 'Pedas Asam Gurih',
                'rating'      => 4.9,
                'image'       => 'gulai-ikan-patin-khas-riau.jpg',
                'is_featured' => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'Gulai Patin Asam Pedas Kampar',
                'slug'        => 'gulai-patin-asam-pedas-kampar',
                'category'    => 'Gulai Spesial',
                'price'       => 48000,
                'description' => 'Olahan khas Kampar tanpa santan dengan kuah merah menyala yang mengombinasikan asam kandis segar, cabai merah keriting, dan terasi pilihan yang sangat menggugah selera.',
                'origin'      => 'Kampar, Riau',
                'spice_level' => 'Pedas Asam Segar',
                'rating'      => 4.8,
                'image'       => 'gulai-patin-asam-pedas-kampar.jpg',
                'is_featured' => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'Gulai Ikan Patin Salai (Asap)',
                'slug'        => 'gulai-ikan-patin-salai-asap',
                'category'    => 'Olahan Patin',
                'price'       => 52000,
                'description' => 'Ikan patin asap (salai) khas Kuantan Singingi yang memiliki tekstur kenyal gurih dan aroma asap yang dipadukan dengan gulai santan pucuk daun ubi.',
                'origin'      => 'Kuantan Singingi, Riau',
                'spice_level' => 'Pedas Asap Gurih',
                'rating'      => 4.9,
                'image'       => 'gulai-ikan-patin-salai.jpg',
                'is_featured' => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'Patin Bakar Bumbu Kuning Riau',
                'slug'        => 'patin-bakar-bumbu-kuning-riau',
                'category'    => 'Bakar & Panggang',
                'price'       => 42000,
                'description' => 'Daging ikan patin segar yang diolesi bumbu kuning rempah melayu dan dibakar di atas bara arang batok kelapa menghasilkan rasa manis gurih dan juicy.',
                'origin'      => 'Siak Sri Indrapura, Riau',
                'spice_level' => 'Sedang Rempah',
                'rating'      => 4.7,
                'image'       => 'patin-bakar-bumbu-kuning.jpg',
                'is_featured' => 0,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'Gulai Kepala Ikan Patin Jumbo',
                'slug'        => 'gulai-kepala-ikan-patin-jumbo',
                'category'    => 'Gulai Utama',
                'price'       => 65000,
                'description' => 'Kepala ikan patin ukuran besar kaya lemak dan gelatin alami, disiram kuah gulai rempah pekat beraroma kecombrang dan rimbang.',
                'origin'      => 'Pekanbaru, Riau',
                'spice_level' => 'Pedas Gurih Melimpah',
                'rating'      => 4.9,
                'image'       => 'gulai-kepala-ikan-patin.jpg',
                'is_featured' => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'Ikan Patin Goreng Sambal Hijau',
                'slug'        => 'ikan-patin-goreng-sambal-hijau',
                'category'    => 'Goreng & Sambal',
                'price'       => 38000,
                'description' => 'Potongan ikan patin digoreng garing renyah diluar dan lembut didalam, disajikan dengan siraman sambal cabai hijau tumbuk kasar dan petai segar.',
                'origin'      => 'Indragiri Hulu, Riau',
                'spice_level' => 'Sangat Pedas',
                'rating'      => 4.7,
                'image'       => 'ikan-patin-goreng-sambal-hijau.jpg',
                'is_featured' => 0,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'Pindang Patin Nanas Riau',
                'slug'        => 'pindang-patin-nanas-riau',
                'category'    => 'Sup & Pindang',
                'price'       => 40000,
                'description' => 'Sup ikan patin bening kekuningan dengan potongan nanas madu segar, daun kemangi, dan asam jawa yang memberikan kesegaran tiada tanding.',
                'origin'      => 'Pelalawan, Riau',
                'spice_level' => 'Asam Manis Pedas',
                'rating'      => 4.8,
                'image'       => 'pindang-patin-nanas.jpg',
                'is_featured' => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'Asam Pedas Ikan Baung Riau',
                'slug'        => 'asam-pedas-ikan-baung-riau',
                'category'    => 'Hidangan Khas Melayu',
                'price'       => 50000,
                'description' => 'Ikan baung sungai khas Riau dengan kuah asam pedas kental berempah jahe, kunyit, dan cabai merah yang kaya antioksidan.',
                'origin'      => 'Rokan Hilir, Riau',
                'spice_level' => 'Pedas Asam',
                'rating'      => 4.8,
                'image'       => 'asam-pedas-ikan-baung.jpg',
                'is_featured' => 0,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'Gulai Belacan Khas Pekanbaru',
                'slug'        => 'gulai-belacan-khas-pekanbaru',
                'category'    => 'Hidangan Khas Melayu',
                'price'       => 45000,
                'description' => 'Olahan gulai udang & ikan patin yang diracik bersama kuah santan terasi (belacan) Riau pilihan bertabur cabai rawit utuh.',
                'origin'      => 'Pekanbaru, Riau',
                'spice_level' => 'Pedas Gurih Belacan',
                'rating'      => 4.7,
                'image'       => 'gulai-belacan.jpg',
                'is_featured' => 0,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('foods')->insertBatch($foods);
    }
}
